BeEngineer/urls.py
from . import settings
from django.conf.urls import url, include
from custom_admin.sites import site
from django.conf.urls.static import static
from member.views import MemberAutocomplete, CourseMemberAutocomplete


urlpatterns = [
    url(r'^autocomplete/member$', MemberAutocomplete.as_view(), name='member-autocomplete',),
    url(r'^autocomplete/course-member$', CourseMemberAutocomplete.as_view(), name='course-member-autocomplete',),
    url(r'^admin/', site.urls),
    url(r'^sls-client/', include('sls.urls', namespace='sls')),
    url(r'^', include('frontend.urls', namespace='frontend')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sls/urls.py
# coding=utf8

from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='home'),
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^course$', views.CourseView.as_view(), name='course'),
    url(r'^course/viewer/(?P<media_id>[0-9]+?)$', views.MediaViewerView.as_view(), name='media_viewer'),
]

course/models.py
# coding=utf8
from __future__ import unicode_literals

from django.db.models import *
from django.db import models as models
from adminsortable.models import SortableMixin
from django.core.validators import MaxValueValidator


class Course(models.Model):

    # Fields
    name = models.CharField(
        max_length=255,
        verbose_name=u'ชื่อ',
        null=False,
        blank=False,
    )
    detail = models.TextField(
        blank=True,
        default='',
        verbose_name=u'รายละเอียด',
    )
    default_hours = models.PositiveIntegerField(
        default=30,
        null=False,
        blank=False,
        verbose_name=u'ชั่วโมงเรียนเริ่มต้น'
    )
    public = models.BooleanField(
        null=False,
        default=True,
        db_index=True,
    )
    created = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )
    last_updated = models.DateTimeField(
        auto_now=True,
        editable=False
    )

    class Meta:
        ordering = ('name',)
        verbose_name = u'วิชาเรียน'
        verbose_name_plural = u'วิชาเรียน'

    def __str__(self):
        return u'%s' % self.name

    def __unicode__(self):
        return u'%s' % self.name


class CourseVideo(SortableMixin):
    course = models.ForeignKey(Course)
    name = models.CharField(
        max_length=255,
        verbose_name=u'ชื่อ',
        null=False,
        blank=False,
    )
    link = models.CharField(
        max_length=1024,
        verbose_name=u'Video Link/URL',
        help_text='เช่น ///Users/user/video/sample.mp4, D:/data/video.mp4, http://www.youtube.com/sample.mp4',
        null=False,
        blank=False,
    )
    minute_length = models.PositiveSmallIntegerField(
        default=0,
        blank=False,
        null=False,
        verbose_name=u'ความยาววีดีโอ (นาที)',
        validators=[MaxValueValidator(59)]
    )
    hour_length = models.PositiveSmallIntegerField(
        default=0,
        blank=False,
        null=False,
        verbose_name=u'ความยาววีดีโอ (ชั่วโมง)',
    )
    position = models.PositiveIntegerField(
        default=0,
        db_index=True,
        editable=False,
    )
    public = models.BooleanField(
        null=False,
        default=True,
        db_index=True,
    )
    created = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )
    last_updated = models.DateTimeField(
        auto_now=True,
        editable=False
    )

    class Meta:
        ordering = ('position',)
        verbose_name = u'วิชาเรียน'
        verbose_name_plural = u'วิชาเรียน'

    def __str__(self):
        return u'%s' % self.name

    def __unicode__(self):
        return u'%s' % self.name

course/forms.py
from django import forms
from .models import course


class courseForm(forms.ModelForm):
    class Meta:
        model = course
        fields = ['name', 'detail']

sls/views.py
from django.views import View
from django.shortcuts import render, redirect, reverse
from app_settings.models import SettingProfile
from member.models import Member, SLSLoginLog, SLSCourseVideoViewHistory
from frontend.user_views import clear_user_session, set_user_session
from frontend.booking_views import get_member
from course.models import Course, CourseVideo
from booking.models import Booking
from datetime import datetime
import dateutil.parser
from . import utils


class BaseLoggedInView(View):

    _default_context = None
    login_url = 'sls:login'

    def dispatch(self, request, *args, **kwargs):
        if 'id' not in request.session:
            return redirect(reverse(self.login_url))

        self.request.user = get_member(request)
        self.member = self.request.user

        return super().dispatch(request, *args, **kwargs)

    def get_default_context(self):
        logout_datetime = self.request.session['logout_datetime']
        login_countdown = dateutil.parser.parse(logout_datetime) - datetime.now()

        if not self._default_context:
            self._default_context = {
                'user': self.member,
                'login_countdown': login_countdown.seconds,
            }

        return self._default_context
    
    def force_logout(self, request):
        return redirect(reverse('sls:logout'))


class LoginView(View):
    template_name = 'sls/login.html'
    login_complete_url = 'sls:course'

    def dispatch(self, request, *args, **kwargs):
        if 'id' in request.session:
            return redirect(reverse(self.login_complete_url))
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        context = {}

        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        if username != '' and password != '':
            try:
                member = Member.objects.get(username=username)
                if not member.is_active:
                    context['user_inactive'] = True
                elif member.check_password(password):
                    (booking, last_period, ) = utils.get_current_course(datetime.now(), member)

                    if not booking:
                        context['no_book'] = True
                    else:
                        set_user_session(request, member)
                        request.session['book_id'] = booking.id
                        logout_datetime = datetime.combine(datetime.today(), last_period.end_time)
                        request.session['logout_datetime'] = logout_datetime.isoformat()
                        
                        login_log = SLSLoginLog(booking=booking)
                        login_log.save()

                        url = reverse(self.login_complete_url)
                        return redirect(url)
                else:
                    context['invalid_password'] = True
            except Member.DoesNotExist:
                context['user_not_found'] = True

            context['username'] = username

        return render(request, self.template_name, context)


class LogoutView(BaseLoggedInView):

    after_logout_url = 'sls:login'

    def get(self, request, *args, **kwargs):
        clear_user_session(request)
        if 'book_id' in request.session:
            del request.session['book_id']
        if 'logout_datetime' in request.session:
            del request.session['logout_datetime']

        url = reverse(self.after_logout_url)
        return redirect(url)


class CourseView(BaseLoggedInView):

    template_name = 'sls/course.html'

    def get(self, request, *args, **kwargs):
        context = self.get_default_context()

        book_id = request.session.get('book_id', None)

        if not book_id:
            return self.force_logout(request)

        try:
            booking = Booking.objects.get(id=book_id)
        except Booking.DoesNotExist:
            booking = None

        if not booking:
            return self.force_logout(request)

        current_course = booking.course
        media_list = current_course.coursevideo_set.filter(public=True)
        view_history_list = SLSCourseVideoViewHistory.objects.filter(
            course_video__course=current_course
        ).values_list('course_video__id', flat=True)

        context = self.get_default_context()
        context.update({
            'video_list': media_list,
            'course': current_course,
            'history_list': view_history_list,
        })

        return render(request, self.template_name, context)


class MediaViewerView(BaseLoggedInView):

    template_name = 'sls/media_viewer.html'

    def get(self, request, media_id, *args, **kwargs):
        context = self.get_default_context()
        try:
            video = CourseVideo.objects.get(id=media_id)
        except CourseVideo.DoesNotExist:
            return redirect(reverse('sls:course'))

        view_log = SLSCourseVideoViewHistory(
            member=self.member,
            course_video=video
        )
        view_log.save()

        settings = SettingProfile.get_default()

        context.update({
            'video': video,
            'media_server_url': settings.sls_media_server
        })
        return render(request, self.template_name, context)

sls/templates/sls/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %} | Be Engineer</title>
  <link rel="stylesheet" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" id="bulma" href="{% static 'css/font.css' %}" />
  <link rel="stylesheet" id="bulma" href="{% static 'css/bulma.css' %}" />
  <link rel="stylesheet" id="bulma" href="{% static 'css/main.css' %}" />
  {% block styles %}{% endblock %}
  <style>
    * {
      -webkit-user-select: none;
      -khtml-user-select: none;
      -moz-user-select: -moz-none;
      -o-user-select: none;
      user-select: none;
    }
    #body-wrapper {
      min-height: 100%;
      position: relative;
    }
  </style>
</head>
<body>
  <div id="body-wrapper">
{% block body %}{% endblock %}
  </div>
{% block scripts %}{% endblock %}
</body>
</html>

sls/templates/sls/course.html
{% extends 'sls/dashboard.html' %}
{% load static %}
{% block title %}บทเรียน{% endblock %}

{% block styles %}
{{ block.super }}
<style>
    td, th {
        vertical-align: middle !important;
    }
</style>
{% endblock %}

{% block content %}
<div>
    <H3>{{ course.name }}</H3>
    <table class="table is-striped">
        <thead>
            <tr>
                <th style="width: 40px; text-align:right;">#</th>
                <th>รายการ</th>
                <th style="width: 100px;"></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </tfoot>
        <tbody>
            {% for video in video_list %}
            <tr>
                <td style="text-align:right;">{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'sls:media_viewer' video.id %}">
                    {% if video.id in history_list %}
                        <span style="color:#fe2057">{{video.name}}</span> <span style="color:#666; font-weight: bold;">(เรียนแล้ว)</span>
                    {% else %}
                        <strong style="color:#fe2057">{{video.name}}</strong>
                    {% endif %}
                    </a>
                    <br/>
                    {% if video.hour_length != 0 %}
                    <span style="color:#666;">{{ video.hour_length }} ชั่วโมง</span>
                    {% endif %}
                    {% if video.minute_length != 0 %}
                    <span style="color:#666;">{{ video.minute_length }} นาที</span>
                    {% endif %}
                </td>
                <td>
                    <a class="button begr-button is-primary" href="{% url 'sls:media_viewer' video.id %}" title="{{video.name}}">
                        <span class="icon">
                            <i class="fa fa-play"></i>
                        </span>
                        <strong>เล่นวีดีโอ</strong>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

sls/templates/sls/dashboard.html
{% extends 'sls/base.html' %}
{% load static %}
{% block title %}Sign In{% endblock %}

{% block styles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'plugins/responsive-slider/responsiveslides.css'%}">
  <style>
    .error {
      color: #e1003a;
      text-align: center;
    }
    .footer {
      background: #293941;
      padding: 10px 0;
      color: #FFF;
      width:100%;
      position:absolute;
      bottom:0;
      left:0;
    }
    #dashboard-body {
      padding-top: 60px;
      padding-bottom: 140px;
    }
  </style>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/dashboard.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script>
  window.LOGOUT_COUNTDOWN = {{login_countdown}};
  $(document).ready(function(){
    setInterval(function() {
      switch(window.LOGOUT_COUNTDOWN) {
        case 600: new Notification("เวลาจะหมดใน 10 นาที");
          break;
        case 300: new Notification("เวลาจะหมดใน 5 นาที");
          break;
        case 0: window.location.href ='{% url 'sls:logout' %}';
          break;
      }

      window.LOGOUT_COUNTDOWN--;
    }, 1000)
  })
</script>
{% endblock %}

{% block body %}
  {% include 'sls/navbar.html' %}
  <div class="section" id="dashboard-body">
    <div class="container">
      <div class="column is-12">
        <div class="content">
        {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </div>
  <footer class="footer">
      <div class="container">
        <div class="column is-12">
          <div class="columns">
            <div class="column is-6">
              <p>© 2017 be-engineer. All rights reserved.</p>
            </div>
            <div class="column is-6">
              <p>
                Facebook Page: <span style="color:#fe2057;">beengineer2012</span>
              </p>
              <p>
                LINE: <span style="color:#fe2057;">@be-engineer</span>
              </p>
          </div>
        </div>
      </div>
  </footer>
{% endblock %}

sls/templates/sls/login.html
{% extends 'sls/base.html' %}
{% load static %}
{% block title %}Sign In{% endblock %}

{% block styles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css'%}">
  <style>
    .error {
      color: #e1003a;
      text-align: center;
    }
  </style>
{% endblock %}

{% block scripts %}
<script>
  function beforeSubmit (e) {
    
    var usernameInput = document.getElementById('username')
    var passwordInput = document.getElementById('password')
    
    if (usernameInput.value.trim().length === 0) {
      return false
    } else if (usernameInput.value.length === 0) {
      return false
    }

    var submitButton = document.getElementById('submit-button')
    submitButton.classList.add('is-loading')

    return true;
  }
</script>
{% endblock %}

{% block body %}
  <div class="login-wrapper columns">
    <div class="column is-8 is-hidden-mobile hero-banner">
      <section class="hero is-fullheight is-dark">
        <div class="hero-body">
          <div class="container section">
            <div class="has-text-right">
              <h1 class="title is-1" style="background-color: rgba(0,0,0,0)">Be Engineer</h1> <br>
              <p class="title is-3" style="background-color: rgba(0,0,0,0)">SLS On-demain System Login</p>
            </div>
          </div>
        </div>
      </section>  
    </div>
    <div class="column is-4">
      <section class="hero is-fullheight">
        <div class="hero-heading">
          <div class="section has-text-centered">
            <img src="{% static 'img/logo.png' %}" alt="Be Engineer logo">
          </div>
        </div>
        <div class="hero-body">
          <div class="container">
            <div class="columns">
              <div class="column is-8 is-offset-2">
                <form class="login-form" method="POST" onsubmit="return beforeSubmit()">
                  {% csrf_token %}
                  <p class="control has-icon has-icon-right">
                    <input id="username" name="username" class="input email-input" type="text" placeholder="jsmith@example.org" value="{{username}}">
                    <span class="icon user">
                      <i class="fa fa-user"></i>
                    </span>
                  </p>
                  <p class="control has-icon has-icon-right">
                    <input id="password" name="password" class="input password-input" type="password" placeholder="●●●●●●●">
                    <span class="icon user">
                      <i class="fa fa-lock"></i>
                    </span>
                  </p>
                  {% if user_not_found %}
                  <p class="control error">ไม่พบ username นี้<p>
                  {% endif %}
                  {% if invalid_password %}
                  <p class="control error">password ไม่ถูกต้อง<p>
                  {% endif %}
                  {% if user_inactive %}
                  <p class="control error">ผู้ใช้ {{username}} ยังใช้งานไม่ได้<p>
                  {% endif %}
                  {% if no_book %}
                  <p class="control error">ผู้ใช้ {{username}} ไม่ได้จองวิชาเรียนในเวลานี้<p>
                  {% endif %}
                  <p class="control login">
                    <button id="submit-button" type="submit" class="button begr-button is-primary is-large is-fullwidth">Login</button>
                  </p>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>  
    </div>
  </div>
{% endblock %}

sls/templates/sls/media_viewer.html
{% extends 'sls/dashboard.html' %}
{% load static %}
{% block title %}บทเรียน{% endblock %}

{% block styles %}
{{ block.super }}
<link href="{% static 'plugins/videojs/video-js.min.css' %}" rel="stylesheet">
<link href="{% static 'plugins/videojs/videojs-seek-buttons.css' %}" rel="stylesheet">

{% endblock %}

{% block content %}
<div>
    <div>
        <a href="{% url 'sls:course' %}">
            <span class="icon">
                <i class="fa fa-list-ul"></i>
            </span>
            &nbsp; รายการ
        </a>
        <span> / </span>
        <strong>{{ video.name }}</strong>
    </div>
    <h1 style="text-align:center;">{{ video.name }}</h1>
    <video
        id="player" class="video-js"
        style="width:100%; min-height:500px;"

    >
        <source src="{{media_server_url}}{{video.link}}" type="video/mp4"></source>
        <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a
            web browser that
            <a href="http://videojs.com/html5-video-support/" target="_blank">
            supports HTML5 video
            </a>
        </p>
    </video>
</div>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript" src="{% static 'plugins/videojs/video.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/videojs/videojs-seek-buttons.js' %}"></script>
<script type="text/javascript" >
window.HELP_IMPROVE_VIDEOJS = false;

$(document).ready(function() {
    var playerEle = document.getElementById('player')
    var player = videojs(playerEle, {
        playbackRates: [1.0, 1.5, 2.0],
        autoplay: true,
        preload: 'auto',
        controls: true,
        plugins: {
            seekButtons: {
              forward: 10,
              back: 10
            }
        }
    })
})
</script>
{% endblock %}

sls/templates/sls/navbar.html
{% load static %}
<style>
  #dashboard-navbar {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    z-index: 100;
  }
</style>
<nav class="nav has-shadow" id="dashboard-navbar">
    <div class="container">
      <div class="nav-left">
        <a class="nav-item" href="{% url 'sls:course' %}">
          <img src="{% static 'img/logo.png' %}" alt="Be-engineer Logo">
        </a>
      </div>
      <span class="nav-toggle">
        <span></span>
        <span></span>
        <span></span>
      </span>
      <div class="nav-right nav-menu">
        <span class="nav-item">
          {% if request.session.picture_url %}
          <figure class="image is-32x32" style="margin-right: 8px;
            background-image: url({{ request.session.picture_url }});
            background-size: cover;">
          </figure>
          {% else %}
          <span style="margin-right: 8px;">
            <i class="fa fa-user" aria-hidden="true"></i>
          </span>
          {% endif %}
          {{ request.session.first_name }} {{ request.session.last_name }}
        </span>
        {% comment %} <a class="nav-item" href="{% url 'edit_profile' %}">
          แก้ไขข้อมูล
        </a>
        <a class="nav-item" href="{% url 'change_password' %}">
          เปลี่ยน password
        </a> {% endcomment %}
        <div class="nav-item">
          <a class="button begr-button is-primary is-outlined" href="{% url 'sls:logout' %}">
            ออกจากระบบ
          </a>
        </div>
        
      </div>
    </div>
  </nav>