BeEngineer/urls.py
from . import settings
from django.conf.urls import url, include
from custom_admin.sites import site
from django.conf.urls.static import static
from member.views import MemberAutocomplete, CourseMemberAutocomplete


urlpatterns = [
    url(r'^autocomplete/member$', MemberAutocomplete.as_view(), name='member-autocomplete',),
    url(r'^autocomplete/course-member$', CourseMemberAutocomplete.as_view(), name='course-member-autocomplete',),
    url(r'^admin/', site.urls),
    url(r'^sls-client/', include('sls.urls', namespace='sls')),
    url(r'^', include('frontend.urls', namespace='frontend')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
# coding=utf8

from django.conf.urls import url, include
from . import user_views, booking_views

urlpatterns = [
    # user
    url(r'^$', user_views.login, name='home_login'),
    url(r'^register$', user_views.register, name='register'),
    url(r'^edit_profile$', user_views.edit_profile, name='edit_profile'),
    url(r'^change_password$', user_views.change_password, name='change_password'),
    url(r'^login$', user_views.login, name='login'),
    url(r'^logout$', user_views.logout, name='logout'),

    # search booking
    url(r'^booking/search$', booking_views.search_booking, 
        name='search_booking'),
    url(r'^booking/book$', booking_views.book, name='book'),
    url(r'^booking/is_free_cancel$',
        booking_views.check_is_free_cancel_booking,
        name='check_is_free_cancel_booking'),
    url(r'^booking/cancel$', booking_views.cancel_booking,
        name='cancel_booking'),

    # booking history
    url(r'^booking/history$', booking_views.history, name='booking_history'),

    # booking schedule
    url(r'^booking/schedule$', booking_views.schedule, name='booking_schedule'),
]

sls/urls.py
# coding=utf8

from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='home'),
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^course$', views.CourseView.as_view(), name='course'),
    url(r'^course/viewer/(?P<media_id>[0-9]+?)$', views.MediaViewerView.as_view(), name='media_viewer'),
]

booking/models.py
# coding=utf8

from django.db import models as models
from member.models import Member, StudyingTimeTransaction
from course.models import Course


class BookingActionEnum:
    BOOKED = 'BOOKED'
    CANCEL_BOOK = 'CANCEL_BOOK'
    CANCEL_LATE_LOGIN = 'CANCEL_LATE_LOGIN'
    CANCEL_DISPLAY = u'ยกเลิก'
    BOOKED_DISPLAY = u'จอง'
    CANCEL_LATE_LOGIN_DISPLAY = u'ยกเลิกเนื่องจากเข้าเรียนสาย'


BOOKING_ACTION_CHOICES = (
    (BookingActionEnum.BOOKED, BookingActionEnum.BOOKED_DISPLAY,),
    (BookingActionEnum.CANCEL_BOOK, BookingActionEnum.CANCEL_DISPLAY,),
    (BookingActionEnum.CANCEL_LATE_LOGIN, BookingActionEnum.CANCEL_LATE_LOGIN_DISPLAY,),
)


class Booking(models.Model):
    date = models.DateField(
        null=False,
        blank=False,
        db_index=True,
        verbose_name=u'วันที่จอง'
    )
    member = models.ForeignKey(
        'member.Member',
    )
    course = models.ForeignKey(
        'course.Course'
    )
    seat = models.ForeignKey(
        'app_settings.Seat',
    )
    action = models.CharField(
        max_length=32,
        null=False,
        default=BookingActionEnum.BOOKED,
        choices=BOOKING_ACTION_CHOICES
    )
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)

    @property
    def display_period(self):
        periods = self.bookingperiod_set.all().select_related().order_by('period__start_time')
        period_list = list(periods)
        start_period = period_list[0].period
        end_period = period_list[-1].period
        return u'%s - %s' % (start_period.start_time.strftime('%H:%M'), end_period.end_time.strftime('%H:%M'), )

    def __str__(self):
        return u'%s %s %s [%s]' % (self.course, self.date, self.display_period, self.seat)

    def __unicode__(self):
        return u'%s' % self.period

    class Meta:
        ordering = ('-created',)
        verbose_name = u'การจอง'
        verbose_name_plural = u'การจอง'


class BookingPeriod(models.Model):
    booking = models.ForeignKey(
        'booking.Booking'
    )
    period = models.ForeignKey(
        'app_settings.Period',
    )
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return u'%s' % self.period

    def __unicode__(self):
        return u'%s' % self.period

    class Meta:
        ordering = ('period__start_time',)
        verbose_name = u'เวลาการจอง'
        verbose_name_plural = u'เวลาการจอง'
        unique_together = ('booking', 'period')


class StudyingTimeTransactionProxy(StudyingTimeTransaction):

    class Meta:
        proxy = True
        ordering = ('-created',)
        verbose_name = u'สถานะใช้เวลาเรียน'
        verbose_name_plural = verbose_name

frontend/templates/frontend/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %} | Be Engineer</title>
  <link rel="stylesheet" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" id="bulma" href="{% static 'css/font.css' %}" />
  <link rel="stylesheet" id="bulma" href="{% static 'css/bulma.css' %}" />
  <link rel="stylesheet" id="bulma" href="{% static 'css/main.css' %}" />
  {% block styles %}{% endblock %}
  <style>
    #body-wrapper {
      min-height: 100%;
      position: relative;
    }
  </style>
</head>
<body>
  <div id="body-wrapper">
{% block body %}{% endblock %}
  </div>
{% block scripts %}{% endblock %}
</body>
</html>

frontend/templates/frontend/booking.html
{% extends 'frontend/dashboard.html' %}
{% load static %}

{% block scripts %}
{{ block.super }}
<script src="{% static 'plugins/flatpickr/flatpickr.js' %}"></script>
<script src="{% static 'plugins/flatpickr/flatpickr.locale.th.js' %}"></script>
<script>
    $(document).ready(function() {
        Flatpickr.localize(Flatpickr.l10ns.th)
        var flatPicker = flatpickr('#datepicker', {
            altInput: true,
            defaultDate: new Date(),
            minDate: new Date(),
        })

        {% if search_params.date %}
        var selectedDate = new Date('{{search_params.date}}')
        selectedDate.setHours(23)
        selectedDate.setMinutes(59)
        flatPicker.setDate(selectedDate)
        {% endif %}

        $('#bookform').on('submit', function(e) {
            var input = $('input[type="radio"]:checked')
            var period_text = input.data('period')
            $('#display-period').text(period_text)
            showConfirmBooking()
            e.preventDefault(true)
            return false;
        })
        $('.result-data input[type="radio"]').click(function(e) {
            e.stopPropagation()
            var self = $(e.target)
            $('.result-data').removeClass('selected')
            self.parent().addClass('selected')
        })
        $('.result-data').click(function(e) {
            e.stopImmediatePropagation()
            var self = $(e.target)
            var inputId = self.data('for')
            $('#' + inputId).click()
        })
    })

    function showConfirmBooking() {
        var confirmModal = document.getElementById('confirm-modal')
        confirmModal.classList.add('is-active')
        
    }
    function closeConfirmBooking() {
        var confirmModal = document.getElementById('confirm-modal')
        confirmModal.classList.remove('is-active')
    }
</script>
{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'plugins/flatpickr/flatpickr.min.css' %}">
<style>
    .result-data:hover {
        cursor: pointer;
    }
    .result-data.selected{
        background: #22343E;
        color: #FFFFFF;
    }
    input[type="radio"] {
        margin: 0 10px;
    }
</style>
{% endblock %}

{% block title %}ค้นหา/จอง วิชาเรียน{% endblock %}

{% block content %}

<div class="modal" id="confirm-modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <div class="modal-card-title">ยืนยันการจอง</div>
      <button class="delete" onclick="closeConfirmBooking()"></button>
    </header>
    <section class="modal-card-body">
        <div class="container">
            <div class="column is-12">
                <div class="columns">
                    <div class="column is-4">คุณต้องการจองวิชา</div>
                    <div class="column is-8"><strong>{{display_params.course_name}}</strong></div>
                </div>
                <div class="columns">
                    <div class="column is-4">ในวันที่</div>
                    <div class="column is-8"><strong>{{display_params.date|date:'l, j F o'}}</strong></div>
                </div>
                <div class="columns">
                    <div class="column is-4">ช่วงเวลา</div>
                    <div class="column is-8"><strong id="display-period"></strong></div>
                </div>
                <div class="columns">
                    <div class="column is-4">เป็นเวลา</div>
                    <div class="column is-8"><strong>{{search_params.duration}} ชั่วโมง</strong></div>
                </div>
                <div class="columns">
                    <div class="column is-12" style="color: #ff3860;">
                        *หากมาสายเกิน 15 นาที ระบบจะตัดเวลาที่จองไว้ทันที
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer class="modal-card-foot">
      <a class="button is-primary begr-button" onclick="window.bookform.submit()">ตกลง</a>
      <a class="button begr-button" onclick="closeConfirmBooking()">ยกเลิก</a>
    </footer>
  </div>
</div>


<h1>ค้นหา/จอง วิชาเรียน</h1>
<form method="POST">
    {% csrf_token %}
    <div class="field is-horizontal">
        <div class="field-label">
            <label class="label sukhumvit-font">วิชาเรียน</label>
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    <span class="select is-fullwidth">
                        <select id="course" name="course">
                            {% for course_member in course_members %}
                            {% with course=course_member.course %}
                            <option value="{{ course.id }}"
                                {% if course.id == search_params.course %}
                                selected
                                {% endif %}
                            >
                                {{ course.name }} 
                                {% if course_member.remaining_studying_hours <= 0 %}
                                (ชั่วโมงเรียนหมดแล้ว)
                                {% else %}
                                (เหลือเวลาเรียน {{course_member.remaining_studying_hours}} ชั่วโมง)
                                {% endif %}
                            </option>
                            {% endwith %}
                            {% endfor %}
                        </select>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="field is-horizontal">
        <div class="field-label">
            <label class="label sukhumvit-font">วันที่เรียน</label>
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    <input id="datepicker" name="date" placeholder="เลือกวันที่เรียน"/>
                </div>
            </div>
        </div>
    </div>
    <div class="field">
        <div class="field-label">
            <label class="label sukhumvit-font">จำนวนชั่วโมง</label>
        </div>
        <div class="control">
            <span class="select is-fullwidth">
                <select id="period" name="duration">
                    <option value="1" {% if search_params.duration == 1 %} selected {% endif %}>1 ชั่วโมง</option>
                    <option value="2" {% if search_params.duration == 2 %} selected {% endif %} {% if not search_params.duration %} selected {% endif %}>2 ชั่วโมง</option>
                    <option value="3" {% if search_params.duration == 3 %} selected {% endif %}>3 ชั่วโมง</option>
                    <option value="4" {% if search_params.duration == 4 %} selected {% endif %}>4 ชั่วโมง</option>
                </select>
            </span>
        </div>
    </div>
    <div class="field">
        <label class="label"></label>
        <div class="control" style="text-align: center;">
            <p style="display:inline-block;">
                <button type="submit" name="addition_date" value="{{prev_date_str}}" class="button is-primary is-outlined"
                    style="
                        width: 100px;
                        float:left;
                        border-bottom-right-radius:0px;
                        border-top-right-radius:0px;
                    "
                    {% if not prev_date_str %}disabled="disabled"{% endif %}
                    >
                    <span class="icon is-small">
                        <i class="fa fa-arrow-left"></i>
                    </span>
                    <span>วันก่อนหน้า</span>
                </button>
                <button type="submit" name="addition_date" value="" class="button is-primary"
                    style="float:left;border-width: 0px; border-radius: 0px;">
                    <span class="icon is-small">
                        <i class="fa fa-search"></i>
                    </span>
                    <span>ค้นหา</span>
                </button>
                <button type="submit" name="addition_date" value="{{next_date_str}}" class="button is-primary is-outlined"
                    style="width: 100px; float:left;
                        border-bottom-left-radius:0px;
                        border-top-left-radius:0px;">
                    <span>วันถัดไป</span>
                    <span class="icon is-small">
                        <i class="fa fa-arrow-right"></i>
                    </span>
                </button>
                <div style="clear:both;"></div>
            </p>
        </div>
    </div>
    
    {% if error_message %}
    <div style="color:brown; text-align:center;">พบข้อผิดพลาดในระหว่างทำการจอง กรุณาตรวจสอบชั่วโมงเรียน หรือช่วงเวลาอีกครั้ง</div>
    {% endif %}
</form>

{% if result %}
<h2>{{display_params.date| date:'วันlที่ j F o'}} (ว่าง {{result|length}} ที่นั่ง)</h2>

<form method="POST" action="{% url 'frontend:book' %}"
                data-start-time="{{r.start_time}}"
                data-end-time="{{r.end_time}}"
                id="bookform">
                {% csrf_token %}
    <input type="hidden" name="date" value="{{search_params.date}}"/>
    <input type="hidden" name="course" value="{{search_params.course}}"/>
    <table class="table is-bordered is-striped">
        <thead>
        <tr>
            <th>ช่วงเวลา</th>
        </tr>
        </thead>
        <tbody>
        {% for r in result %}
        <tr>
            <td class="result-data" data-for="booking-result-{{ forloop.counter }}">
                <input id="booking-result-{{ forloop.counter }}"
                    type="radio" name="period_id_list"
                    value="{{r.period_id_list|join:','}}"
                    data-period="{{r.start_time|time:'H:i'}} - {{r.end_time|time:'H:i'}}"/>
                <label for="booking-result-{{ forloop.counter }}">
                    {{r.start_time|time:'H:i'}} - {{r.end_time|time:'H:i'}}
                </label>
            </td>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <button type="submit" class="button is-primary begr-button">จอง</button>
    </form>
{% endif %}
{% if result_not_found %}
    <h3>ไม่พบชั่วโมงเรียนที่ค้นหา</h3>
{% endif %}

{% endblock %}

frontend/templates/frontend/booking_history.html
{% extends 'frontend/dashboard.html' %}
{% load static %}
{% block title %}ประวัติการเรียน{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" id="bulma" href="{% static 'css/booking.css' %}" />
{% endblock %}

{% block content %}
<h1>ประวัติการเรียน</h1>
{% for history in history_list %}
<div class="booking-list history-list">
  <div class="booking-item">
    <div class="booking-date-wrapper">
      <div class="booking-weekday reverse">{{ history.date | date:'l' }}</div>
      <div class="booking-date reverse">{{ history.date | date:'j' }}</div>
      <div class="booking-month reverse">{{ history.date | date:'F' }}</div>
    </div>
    <div class="booking-body">
      <div class="wrapper" style="display: inline-block;">
        <div class="booking-subject">{{ history.course }}</div>
        <div class="booking-period">{{ history.display_period }}</div>
      </div>
      <div class="booking-remark has-text-centered">
        {% if history.action == 'CANCEL_BOOK' %}
            <span style="color: #ff3860;">*{{history.get_action_display}}</span>
        {% endif %}
      </div>
      <div class="booking-seat">
        <div class="booking-seat-label">ที่นั่ง</div>
        <div class="booking-seat-number">{{ history.seat }}</div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}

frontend/templates/frontend/booking_schedule.html
{% extends 'frontend/dashboard.html' %}
{% load static %}

{% block title %}ตารางการจอง{% endblock %}
{% block scripts %}
{{ block.super }}
<script>
  window.activeBooking = {}
  // using jQuery
  function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
              var cookie = jQuery.trim(cookies[i]);
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
  }

  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  
  }

  $(document).ready(function(){
    var csrftoken = getCookie('csrftoken');
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });

    $('.cancel-booking').click(function(e){
      var elm = $(e.target)
      var booking_id = elm.data('id')
      window.activeBooking.id = booking_id
      window.activeBooking.period = elm.data('period')
      window.activeBooking.course = elm.data('course')
      window.activeBooking.date = elm.data('date')
      var url = '{% url 'frontend:check_is_free_cancel_booking' %}'

      $.post(url, {
        booking_id: booking_id
      }, function(body, status){
        if(body.status === 'success') {
          showConfirmCancelBooking(body.data.is_free)
        }
      })
    })
  })

  function showConfirmCancelBooking(isFree) {
    var modal = $('#confirm-modal')
    $('#booking-course').text(window.activeBooking.course)
    $('#booking-date').text(window.activeBooking.date)
    $('#booking-period').text(window.activeBooking.period)
    if (isFree) {
      $('#free-cancel-message').show()
      $('#not-free-cancel-message').hide()
    } else {
      $('#free-cancel-message').hide()
      $('#not-free-cancel-message').show()
    }

    modal.addClass('is-active')
  }

  function hideConfirmCancelBooking() {
    var modal = $('#confirm-modal')
    modal.removeClass('is-active')
  }
  function cancelBooking() {
    var form = $('#cancel-form')
    form.find('[name="booking_id"]').val(window.activeBooking.id)
    form.submit()
  }
</script>
{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" id="bulma" href="{% static 'css/booking.css' %}" />
<style>
  #free-cancel-message, #not-free-cancel-message {
    color: #ff3860;
  }
  .highlight-brown {
    color:#b32f2f;
    text-decoration: underline;
    font-weight: bold;
  }
  .cancel-booking {
    width:40px;
    border-radius: 8px;
    font-size:14px;
  }
</style>
{% endblock %}
{% block content %}
<h1>ตารางการจอง</h1>

{% for book in book_list %}

<div class="booking-list">
  <div class="booking-item">
    <div class="booking-date-wrapper">
      <div class="booking-weekday">{{ book.date | date:'l' }}</div>
      <div class="booking-date">{{ book.date | date:'j' }}</div>
      <div class="booking-month">{{ book.date | date:'F' }}</div>
    </div>
    <div class="booking-body">
      <div class="wrapper" style="display: inline-block;">
        <div class="booking-subject">{{ book.course }}</div>
        <div class="booking-period">{{ book.display_period }}</div>
      </div>
      <div class="booking-seat">
        <div class="booking-seat-label">ที่นั่ง</div>
        <div class="booking-seat-number">{{ book.seat }}</div>
      </div>
    </div>
    <div class="booking-action">
          <button type="button" class="button is-danger cancel-booking"
            data-id="{{book.id}}"
            data-date="{{ book.date | date:'j F o' }}"
            data-course="{{ book.course }}"
            data-period="{{ book.display_period }}"
          >
            ยกเลิก
          </button>
    </div>
  </div>
</div>
{% endfor %}

  <form id="cancel-form" action="{% url 'frontend:cancel_booking' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="booking_id" value=""/>
  </form>

  <div class="modal" id="confirm-modal">
    <div class="modal-background"></div>
    <div class="modal-card">
      <header class="modal-card-head">
        <div class="modal-card-title">ยืนยันการยกเลิก</div>
        <button class="delete" onclick="hideConfirmCancelBooking()"></button>
      </header>
      <section class="modal-card-body">
          <div class="container">
              <div class="column is-12">
                  <div class="columns">
                      <div class="column is-4">วิชา</div>
                      <div class="column is-8"><strong id="booking-course"></strong></div>
                  </div>
                  <div class="columns">
                      <div class="column is-4">ในวันที่</div>
                      <div class="column is-8"><strong id="booking-date"></strong></div>
                  </div>
                  <div class="columns">
                      <div class="column is-4">ช่วงเวลา</div>
                      <div class="column is-8"><strong id="booking-period"></strong></div>
                  </div>
                  <div class="columns">
                    <div class="column is-12" id="free-cancel-message" style="display:none;">
                      *นักเรียนจะ <span class="highlight-brown">ได้รับ</span> เวลาเรียนคืนหลังจากทำการยกเลิกการจอง
                    </div>
                    <div class="column is-12" id="not-free-cancel-message" style="display:none;">
                      *นักเรียนจะ <span class="highlight-brown">ไม่ได้รับ</span> เวลาเรียนคืนเนื่องจากเลยเวลาในการยกเลิก
                    </div>
                  </div>
              </div>
          </div>
      </section>
      <footer class="modal-card-foot">
        <a class="button begr-button is-danger" onclick="cancelBooking()">ยกเลิกการจอง</a>
        <a class="button begr-button" onclick="hideConfirmCancelBooking()">ยกเลิก</a>
      </footer>
    </div>
  </div>
{% endblock %}

frontend/templates/frontend/login.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block title %}Sign In{% endblock %}

{% block styles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css'%}">
  <style>
    .error {
      color: #e1003a;
      text-align: center;
    }
  </style>
{% endblock %}

{% block scripts %}
<script>
  function beforeSubmit (e) {
    
    var usernameInput = document.getElementById('username')
    var passwordInput = document.getElementById('password')
    
    if (usernameInput.value.trim().length === 0) {
      return false
    } else if (usernameInput.value.length === 0) {
      return false
    }

    var submitButton = document.getElementById('submit-button')
    submitButton.classList.add('is-loading')

    return true;
  }
</script>
{% endblock %}

{% block body %}
  <div class="login-wrapper columns">
    <div class="column is-8 is-hidden-mobile hero-banner">
      <section class="hero is-fullheight is-dark">
        <div class="hero-body">
          <div class="container section">
            <div class="has-text-right">
              <h1 class="title is-1" style="background-color: rgba(0,0,0,0)">Login</h1> <br>
              <p class="title is-3" style="background-color: rgba(0,0,0,0)">Be Engineer Booking System Login</p>
            </div>
          </div>
        </div>
      </section>  
    </div>
    <div class="column is-4">
      <section class="hero is-fullheight">
        <div class="hero-heading">
          <div class="section has-text-centered">
            <img src="{% static 'img/logo.png' %}" alt="Be Engineer logo">
          </div>
        </div>
        <div class="hero-body">
          <div class="container">
            <div class="columns">
              <div class="column is-8 is-offset-2">
                <form class="login-form" method="POST" onsubmit="return beforeSubmit()">
                  {% csrf_token %}
                  <p class="control has-icon has-icon-right">
                    <input id="username" name="username" class="input email-input" type="text" placeholder="jsmith@example.org" value="{{username}}">
                    <span class="icon user">
                      <i class="fa fa-user"></i>
                    </span>
                  </p>
                  <p class="control has-icon has-icon-right">
                    <input id="password" name="password" class="input password-input" type="password" placeholder="●●●●●●●">
                    <span class="icon user">
                      <i class="fa fa-lock"></i>
                    </span>
                  </p>
                  {% if user_not_found %}
                  <p class="control error">ไม่พบ username นี้<p>
                  {% endif %}
                  {% if invalid_password %}
                  <p class="control error">password ไม่ถูกต้อง<p>
                  {% endif %}
                  {% if user_inactive %}
                  <p class="control error">ผู้ใช้ {{username}} ยังใช้งานไม่ได้<p>
                  {% endif %}
                  <p class="control login">
                    <button id="submit-button" type="submit" class="button begr-button is-primary is-large is-fullwidth">Login</button>
                  </p>
                  <p style="text-align: center">
                    <a href="{% url 'frontend:register' %}">สมัครสมาชิก</a>
                  </p>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>  
    </div>
  </div>
{% endblock %}

frontend/templates/frontend/navbar.html
{% load static %}
<style>
  #dashboard-navbar {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    z-index: 100;
  }
</style>
<nav class="nav has-shadow" id="dashboard-navbar">
    <div class="container">
      <div class="nav-left">
        <a class="nav-item" href="{% url 'frontend:search_booking' %}">
          <img src="{% static 'img/logo.png' %}" alt="Be-engineer Logo">
        </a>
      </div>
      <span class="nav-toggle">
        <span></span>
        <span></span>
        <span></span>
      </span>
      <div class="nav-right nav-menu">
        <span class="nav-item">
          {% if request.session.picture_url %}
          <figure class="image is-32x32" style="margin-right: 8px;
            background-image: url({{ request.session.picture_url }});
            background-size: cover;">
          </figure>
          {% else %}
          <span style="margin-right: 8px;">
            <i class="fa fa-user" aria-hidden="true"></i>
          </span>
          {% endif %}
          {{ request.session.first_name }} {{ request.session.last_name }}
        </span>
        <a class="nav-item" href="{% url 'frontend:edit_profile' %}">
          แก้ไขข้อมูล
        </a>
        <a class="nav-item" href="{% url 'frontend:change_password' %}">
          เปลี่ยน password
        </a>
        <div class="nav-item">
          <a class="button begr-button is-primary is-outlined" href="{% url 'frontend:logout' %}">
            ออกจากระบบ
          </a>
        </div>
        
      </div>
    </div>
  </nav>

frontend/templates/frontend/side_menu.html
{% load static %}

<div class="column is-4">
    <nav class="panel">
        <a class="panel-block {% if selected_menu == 'search' %}is-active{% endif %}"
            href="{% url 'frontend:search_booking' %}">
            <span class="panel-icon">
                <i class="fa fa-search" aria-hidden="true"></i>
            </span>
            ค้นหา/จอง วิชาเรียน
        </a>
        <a class="panel-block {% if selected_menu == 'schedule' %}is-active{% endif %}"
            href="{% url 'frontend:booking_schedule' %}">
            <span class="panel-icon">
                {% if selected_menu == 'schedule' %}
                <img src="{% static 'img/icons/schedule-active.png' %}"/>
                {% else %}
                <img src="{% static 'img/icons/schedule.png' %}"/>
                {% endif %}
            </span>
            ตารางการจอง
            </a>
        <a class="panel-block {% if selected_menu == 'history' %}is-active{% endif %}"
            href="{% url 'frontend:booking_history' %}">
            <span class="panel-icon">
                    {% if selected_menu == 'history' %}
                    <img src="{% static 'img/icons/history-active.png' %}"/>
                    {% else %}
                    <img src="{% static 'img/icons/history.png' %}"/>
                    {% endif %}
            </span>
            ประวัติการเรียน
        </a>
        {% for course in course_member %}
        <div class="panel-heading">
            <div class="indent">
                <div>
                    <strong>{{course.course}}</strong>
                </div>
                <div>
                    <span class="mute">(เหลือเวลา <span class="highlight">{{course.remaining_studying_hours}} ชั่วโมง</span>)</span>
                </div>
            </div>
        </div>
        {% endfor %}
    </nav>
</div>